"""parts_manifest.json + lesson_gate.js — derived from the authored English lessons.

The HSK bot builds these from its seed scripts (scripts/seed_hsk*_lesson_*.py).
This course has no seeds: lessons are authored straight into
app/static/course_v3_data/<level>/lesson_NN.json, so we read those instead.

Mini-parts are not split yet — every lesson is one part, so the flat part number
equals the lesson number and completed_lessons_count keeps its current meaning.
Splitting a lesson into 3-4 word chunks is a content change; once the lessons
carry chunk markers, only build_plan() below needs to change.

    python3 scripts/gen_course_v3_derived.py [--dry]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

BASE = Path("app/static/course_v3_data")
LEVELS = ["hsk1", "hsk2", "hsk3", "hsk4"]


def load_lessons(level: str) -> list[dict]:
    """Authored lesson files for a level, in lesson order."""
    folder = BASE / level
    if not folder.is_dir():
        return []
    out = []
    for path in sorted(folder.glob("lesson_*.json")):
        try:
            out.append(json.loads(path.read_text(encoding="utf-8")))
        except Exception as exc:  # noqa: BLE001 — a broken file must not hide the rest
            print(f"!! skipped {path}: {exc}")
    return out


def build_plan() -> dict[str, dict]:
    """level -> {total, lessons:[{src, title, words, parts, checkpoint}]}."""
    plan: dict[str, dict] = {}
    for level in LEVELS:
        flat = 0
        lessons = []
        for lesson in load_lessons(level):
            flat += 1
            words = lesson.get("active_words") or []
            lessons.append({
                "src": int(lesson.get("lesson_id") or flat),
                "title": str(lesson.get("title") or ""),
                "words": words,
                "parts": [flat],
                "checkpoint": flat,
            })
        plan[level] = {"lessons": lessons, "total": flat}
    return plan


def write_parts_manifest(plan: dict, dry: bool = False) -> None:
    out = {
        level: {
            "total_parts": data["total"],
            "lessons": [{
                "src": les["src"],
                "zh": les["title"],
                "words": len(les["words"]),
                "parts": les["parts"],
                "checkpoint": les["checkpoint"],
            } for les in data["lessons"]],
        }
        for level, data in plan.items() if data["total"]
    }
    path = BASE / "parts_manifest.json"
    text = json.dumps(out, ensure_ascii=False, indent=2) + "\n"
    if dry:
        print(f"[dry] {path}: " + ", ".join(f"{k}={v['total_parts']}" for k, v in out.items()))
        return
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}: " + ", ".join(f"{k}={v['total_parts']}" for k, v in out.items()))


def write_lesson_gate(plan: dict, dry: bool = False) -> None:
    """word -> [level number, part number] at its first taught position.

    The practice pages (recognition / pronunciation) use this to keep drills
    inside what the learner has actually studied.
    """
    words: dict[str, list[int]] = {}
    for level, data in plan.items():
        lvl = int(level.replace("hsk", "") or 1)
        for les in data["lessons"]:
            for word in les["words"]:
                term = str(word.get("zh") or "").strip()
                if term and term not in words:
                    words[term] = [lvl, les["parts"][0]]
    text = (
        "/* GENERATED by scripts/gen_course_v3_derived.py — word -> [level, part]\n"
        "   (first place it is taught). Do not edit by hand. */\n"
        "window.HSK_WORD_GATE=" + json.dumps(words, ensure_ascii=False, separators=(",", ":")) + ";\n"
        "window.HSK_CHAR_GATE={};\n"
    )
    path = BASE / "lesson_gate.js"
    if dry:
        print(f"[dry] {path}: words={len(words)}")
        return
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}: words={len(words)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry", action="store_true", help="report without writing")
    args = ap.parse_args()
    plan = build_plan()
    write_parts_manifest(plan, dry=args.dry)
    write_lesson_gate(plan, dry=args.dry)


if __name__ == "__main__":
    main()
