# -*- coding: utf-8 -*-
# Compact lesson curricula. The generator (gen_lessons.py) expands each into a
# full V3 lesson JSON. Word tuple: (en, ipa, pos, uz, ru, tj).


def L(uz, ru, tj):
    return {"uz": uz, "ru": ru, "tj": tj}


SPECS = [
    {
        "level": "hsk1", "id": 7, "title": "Colors",
        "sub": L("Ranglar va sifat sifatida ishlatish", "Цвета и их использование", "Рангҳо ва истифодаи онҳо"),
        "manifest": {"title": "Colors", "py": "/ˈkʌlərz/", "tr": L("Ranglar va sifatlar", "Цвета и прилагательные", "Рангҳо ва сифатҳо")},
        "words": [
            ("color", "/ˈkʌlər/", "n.", "rang", "цвет", "ранг"),
            ("red", "/red/", "adj.", "qizil", "красный", "сурх"),
            ("blue", "/bluː/", "adj.", "ko'k", "синий", "кабуд"),
            ("green", "/ɡriːn/", "adj.", "yashil", "зелёный", "сабз"),
            ("yellow", "/ˈjeloʊ/", "adj.", "sariq", "жёлтый", "зард"),
            ("black", "/blæk/", "adj.", "qora", "чёрный", "сиёҳ"),
            ("white", "/waɪt/", "adj.", "oq", "белый", "сафед"),
            ("this is", "/ðɪs ɪz/", "expr.", "bu ...", "это ...", "ин ..."),
        ],
        "grammar": [
            {"title": L("Rang — sifat", "Цвет — прилагательное", "Ранг — сифат"), "title_en": "color as adjective",
             "rule": L("Rang otdan oldin keladi: a red car.\nMisol: a blue book, a green tree.", "Цвет стоит перед словом: a red car.\nПример: a blue book.", "Ранг пеш аз калима: a red car.\nМисол: a blue book.")},
            {"title": L("Qanday rang?", "Какой цвет?", "Кадом ранг?"), "title_en": "what color",
             "rule": L("So'rash: What color is it?\nJavob: It is red. / It's red.", "Спросить: What color is it?\nОтвет: It is red.", "Пурсидан: What color is it?\nҶавоб: It is red.")},
        ],
        "sentence_builder": {"sentence": L("«Qizil mashina.»", "«Красная машина.»", "«Мошини сурх.»"), "tokens": ["car", "a", "blue", "red"], "answer_tokens": ["a", "red", "car"], "explanation": L("Rang otdan oldin.", "Цвет перед словом.", "Ранг пеш аз калима.")},
        "quiz_grammar": {"prompt": L("«Ko'k» — inglizchada qaysi?", "«Синий» — как по-английски?", "«Кабуд» — ба англисӣ кадом?"), "options": ["green", "blue", "red", "black"], "correct_index": 1},
        "listen_practice": {"audio_text": "It is red.", "pinyin": "/ɪt ɪz red/", "options": ["It is blue.", "It is red.", "It is green.", "It is white."], "correct_index": 1, "explanation": L("red = qizil.", "red = красный.", "red = сурх.")},
        "pronunciation": {"phrase": "It is a blue car", "pinyin": "/ɪt ɪz ə bluː kɑːr/", "translation": L("Bu ko'k mashina", "Это синяя машина", "Ин мошини кабуд")},
        "listen_dialog": {"audio_text": "What color is it?", "pinyin": "/wɒt ˈkʌlər ɪz ɪt/", "options": ["What color is it?", "It is red.", "This is green.", "A white book."], "correct_index": 0, "explanation": L("What color = qanday rang.", "What color = какой цвет.", "What color = кадом ранг.")},
        "gap_fill": {"sentence": "It ____ green.", "options": ["am", "is", "are", "color"], "correct_index": 1, "explanation": L("It is ... — 'is' ishlatiladi.", "It is ... — 'is'.", "It is ... — 'is'.")},
        "dialog_cloze": {"lines": [{"speaker": "A", "zh": "What color is it?", "blank": False}, {"speaker": "B", "zh": "", "blank": True}], "options": ["It is blue.", "Nice to meet you!", "I am ten.", "Good morning!"], "correct_index": 0, "explanation": L("Rangni 'It is ...' bilan aytamiz.", "Цвет — 'It is ...'.", "Ранг — 'It is ...'.")},
        "quiz_dialog": {"prompt": L("Qaysi biri rang emas?", "Что не цвет?", "Кадомаш ранг нест?"), "options": ["red", "blue", "color", "green"], "correct_index": 2},
        "dialogues": [
            {"scene": L("Rang haqida", "О цвете", "Дар бораи ранг"), "lines": [("A", "What color is it?", "/wɒt ˈkʌlər ɪz ɪt/", "Bu qanday rang?", "Какой это цвет?", "Ин кадом ранг аст?"), ("B", "It is red.", "/ɪt ɪz red/", "Bu qizil.", "Это красный.", "Ин сурх аст.")]},
            {"scene": L("Sevimli rang", "Любимый цвет", "Ранги дӯстдошта"), "lines": [("A", "I like blue.", "/aɪ laɪk bluː/", "Menga ko'k yoqadi.", "Мне нравится синий.", "Ба ман кабуд маъқул."), ("B", "I like green.", "/aɪ laɪk ɡriːn/", "Menga yashil yoqadi.", "Мне нравится зелёный.", "Ба ман сабз маъқул.")]},
            {"scene": L("Do'kon", "Магазин", "Дӯкон"), "lines": [("A", "A white shirt, please.", "/ə waɪt ʃɜːrt pliːz/", "Oq ko'ylak, iltimos.", "Белую рубашку, пожалуйста.", "Куртаи сафед, лутфан."), ("B", "Here you are!", "/hɪr juː ɑːr/", "Mana!", "Вот!", "Мана!")]},
        ],
    },
    {
        "level": "hsk1", "id": 8, "title": "Common verbs",
        "sub": L("Kundalik fe'llar va Present Simple", "Повседневные глаголы и Present Simple", "Феълҳои ҳаррӯза ва Present Simple"),
        "manifest": {"title": "Common verbs", "py": "/vɜːrbz/", "tr": L("Kundalik fe'llar", "Повседневные глаголы", "Феълҳои ҳаррӯза")},
        "words": [
            ("go", "/ɡoʊ/", "v.", "bormoq", "идти, ехать", "рафтан"),
            ("come", "/kʌm/", "v.", "kelmoq", "приходить", "омадан"),
            ("see", "/siː/", "v.", "ko'rmoq", "видеть", "дидан"),
            ("read", "/riːd/", "v.", "o'qimoq", "читать", "хондан"),
            ("like", "/laɪk/", "v.", "yoqtirmoq", "нравиться", "маъқул будан"),
            ("have", "/hæv/", "v.", "ega bo'lmoq", "иметь", "доштан"),
            ("work", "/wɜːrk/", "v.", "ishlamoq", "работать", "кор кардан"),
            ("live", "/lɪv/", "v.", "yashamoq", "жить", "зиндагӣ кардан"),
        ],
        "grammar": [
            {"title": L("Present Simple (I/you/we)", "Present Simple (I/you/we)", "Present Simple (I/you/we)"), "title_en": "present simple",
             "rule": L("I go. You read. We work.\nHar kuni takrorlanadigan ish uchun.\nMisol: I like tea.", "I go. You read. We work.\nДля регулярных действий.\nПример: I like tea.", "I go. You read. We work.\nБарои амали ҳаррӯза.\nМисол: I like tea.")},
            {"title": L("He/She + -s", "He/She + -s", "He/She + -s"), "title_en": "third person -s",
             "rule": L("He/She/It bilan fe'lga -s qo'shiladi.\nHe works. She reads. He lives.", "С He/She/It к глаголу +s.\nHe works. She reads.", "Бо He/She/It ба феъл +s.\nHe works. She reads.")},
        ],
        "sentence_builder": {"sentence": L("«Men choy yoqtiraman.»", "«Мне нравится чай.»", "«Ба ман чой маъқул.»"), "tokens": ["like", "go", "I", "tea"], "answer_tokens": ["I", "like", "tea"], "explanation": L("I like ... — yoqtirishni bildiradi.", "I like ... — нравится.", "I like ... — маъқул будан.")},
        "quiz_grammar": {"prompt": L("«She ___ books» — qaysi to'g'ri?", "«She ___ books» — что правильно?", "«She ___ books» — кадом дуруст?"), "options": ["read", "reads", "reading", "to read"], "correct_index": 1},
        "listen_practice": {"audio_text": "I like tea.", "pinyin": "/aɪ laɪk tiː/", "options": ["I go home.", "I like tea.", "I read a book.", "I see you."], "correct_index": 1, "explanation": L("like = yoqtirmoq.", "like = нравиться.", "like = маъқул будан.")},
        "pronunciation": {"phrase": "I read a book", "pinyin": "/aɪ riːd ə bʊk/", "translation": L("Men kitob o'qiyman", "Я читаю книгу", "Ман китоб мехонам")},
        "listen_dialog": {"audio_text": "Where do you work?", "pinyin": "/wer duː juː wɜːrk/", "options": ["Where do you work?", "I like tea.", "I go home.", "She reads."], "correct_index": 0, "explanation": L("work = ishlamoq.", "work = работать.", "work = кор кардан.")},
        "gap_fill": {"sentence": "He ____ in a shop.", "options": ["work", "works", "working", "worked"], "correct_index": 1, "explanation": L("He + fe'l + s: works.", "He + глагол + s: works.", "He + феъл + s: works.")},
        "dialog_cloze": {"lines": [{"speaker": "A", "zh": "Do you like tea?", "blank": False}, {"speaker": "B", "zh": "", "blank": True}], "options": ["Yes, I like tea.", "Goodbye!", "It is red.", "I am ten."], "correct_index": 0, "explanation": L("'Do you like...?' ga 'Yes, I like...' javob.", "На 'Do you like...?' — 'Yes, I like...'.", "Ба 'Do you like...?' — 'Yes, I like...'.")},
        "quiz_dialog": {"prompt": L("Qaysi biri fe'l emas?", "Что не глагол?", "Кадомаш феъл нест?"), "options": ["go", "see", "color", "work"], "correct_index": 2},
        "dialogues": [
            {"scene": L("Ish haqida", "О работе", "Дар бораи кор"), "lines": [("A", "Where do you work?", "/wer duː juː wɜːrk/", "Qayerda ishlaysiz?", "Где вы работаете?", "Дар куҷо кор мекунед?"), ("B", "I work in a shop.", "/aɪ wɜːrk ɪn ə ʃɒp/", "Men do'konda ishlayman.", "Я работаю в магазине.", "Ман дар дӯкон кор мекунам.")]},
            {"scene": L("Qiziqishlar", "Интересы", "Шавқу рағбат"), "lines": [("A", "Do you like reading?", "/duː juː laɪk ˈriːdɪŋ/", "O'qishni yoqtirasizmi?", "Вы любите читать?", "Хонданро дӯст медоред?"), ("B", "Yes, I read every day.", "/aɪ riːd ˈevri deɪ/", "Ha, har kuni o'qiyman.", "Да, я читаю каждый день.", "Бале, ҳар рӯз мехонам.")]},
            {"scene": L("Uchrashuv", "Встреча", "Вохӯрӣ"), "lines": [("A", "See you tomorrow!", "/siː juː təˈmɒroʊ/", "Ertaga ko'rishguncha!", "До завтра!", "То фардо!"), ("B", "Come at ten, please.", "/kʌm æt ten pliːz/", "O'nda keling, iltimos.", "Приходите в десять.", "Соати даҳ биёед.")]},
        ],
    },
    {
        "level": "hsk1", "id": 9, "title": "Places",
        "sub": L("Joylar va 'go to' iborasi", "Места и фраза 'go to'", "Ҷойҳо ва ибораи 'go to'"),
        "manifest": {"title": "Places", "py": "/ˈpleɪsɪz/", "tr": L("Joylar va go to", "Места и go to", "Ҷойҳо ва go to")},
        "words": [
            ("home", "/hoʊm/", "n.", "uy", "дом", "хона"),
            ("school", "/skuːl/", "n.", "maktab", "школа", "мактаб"),
            ("shop", "/ʃɒp/", "n.", "do'kon", "магазин", "дӯкон"),
            ("city", "/ˈsɪti/", "n.", "shahar", "город", "шаҳр"),
            ("here", "/hɪr/", "adv.", "bu yerda", "здесь", "ин ҷо"),
            ("there", "/ðer/", "adv.", "u yerda", "там", "он ҷо"),
            ("go to", "/ɡoʊ tuː/", "expr.", "...ga bormoq", "идти в", "рафтан ба"),
            ("where", "/wer/", "adv.", "qayerda", "где", "куҷо"),
        ],
        "grammar": [
            {"title": L("go to + joy", "go to + место", "go to + ҷой"), "title_en": "go to place",
             "rule": L("I go to school. I go to the shop.\n'home' bilan 'to' kerak emas: go home.", "I go to school. I go to the shop.\nС 'home' без 'to': go home.", "I go to school.\nБо 'home' 'to' лозим нест: go home.")},
            {"title": L("Where is ...?", "Where is ...?", "Where is ...?"), "title_en": "where is",
             "rule": L("So'rash: Where is the shop?\nJavob: It is here. / It is there.", "Спросить: Where is the shop?\nОтвет: It is here.", "Пурсидан: Where is the shop?\nҶавоб: It is here.")},
        ],
        "sentence_builder": {"sentence": L("«Men maktabga boraman.»", "«Я иду в школу.»", "«Ман ба мактаб меравам.»"), "tokens": ["to", "go", "I", "school", "here"], "answer_tokens": ["I", "go", "to", "school"], "explanation": L("go to + joy.", "go to + место.", "go to + ҷой.")},
        "quiz_grammar": {"prompt": L("«Uy» — inglizchada qaysi?", "«Дом» — как по-английски?", "«Хона» — ба англисӣ кадом?"), "options": ["school", "home", "shop", "city"], "correct_index": 1},
        "listen_practice": {"audio_text": "I go to school.", "pinyin": "/aɪ ɡoʊ tuː skuːl/", "options": ["I go home.", "I go to school.", "It is here.", "Where is it?"], "correct_index": 1, "explanation": L("go to school = maktabga bormoq.", "go to school = идти в школу.", "go to school = ба мактаб рафтан.")},
        "pronunciation": {"phrase": "I go to the shop", "pinyin": "/aɪ ɡoʊ tuː ðə ʃɒp/", "translation": L("Men do'konga boraman", "Я иду в магазин", "Ман ба дӯкон меравам")},
        "listen_dialog": {"audio_text": "Where is the school?", "pinyin": "/wer ɪz ðə skuːl/", "options": ["Where is the school?", "I go home.", "It is here.", "Come here!"], "correct_index": 0, "explanation": L("Where = qayerda.", "Where = где.", "Where = куҷо.")},
        "gap_fill": {"sentence": "I go ____ school.", "options": ["to", "in", "at", "home"], "correct_index": 0, "explanation": L("go to + joy.", "go to + место.", "go to + ҷой.")},
        "dialog_cloze": {"lines": [{"speaker": "A", "zh": "Where is the shop?", "blank": False}, {"speaker": "B", "zh": "", "blank": True}], "options": ["It is there.", "Good morning!", "I am ten.", "Thank you!"], "correct_index": 0, "explanation": L("Joyni 'It is here/there' bilan.", "Место — 'It is here/there'.", "Ҷой — 'It is here/there'.")},
        "quiz_dialog": {"prompt": L("Qaysi biri joy emas?", "Что не место?", "Кадомаш ҷой нест?"), "options": ["school", "shop", "where", "home"], "correct_index": 2},
        "dialogues": [
            {"scene": L("Yo'nalish", "Направление", "Самт"), "lines": [("A", "Where is the shop?", "/wer ɪz ðə ʃɒp/", "Do'kon qayerda?", "Где магазин?", "Дӯкон куҷост?"), ("B", "It is there.", "/ɪt ɪz ðer/", "U yerda.", "Там.", "Он ҷо.")]},
            {"scene": L("Kunlik yo'l", "Ежедневный путь", "Роҳи ҳаррӯза"), "lines": [("A", "I go to school every day.", "/aɪ ɡoʊ tuː skuːl/", "Men har kuni maktabga boraman.", "Я хожу в школу каждый день.", "Ман ҳар рӯз ба мактаб меравам."), ("B", "Me too!", "/miː tuː/", "Men ham!", "Я тоже!", "Ман ҳам!")]},
            {"scene": L("Taklif", "Приглашение", "Даъват"), "lines": [("A", "Come here, please.", "/kʌm hɪr pliːz/", "Bu yerga keling.", "Идите сюда.", "Ин ҷо биёед."), ("B", "OK, I come!", "/oʊ ˈkeɪ aɪ kʌm/", "Xo'p, kelaman!", "Хорошо, иду!", "Хуб, меоям!")]},
        ],
    },
    {
        "level": "hsk1", "id": 10, "title": "Time",
        "sub": L("Vaqt, soat va 'What time'", "Время, часы и 'What time'", "Вақт, соат ва 'What time'"),
        "manifest": {"title": "Time", "py": "/taɪm/", "tr": L("Vaqt va soat", "Время и часы", "Вақт ва соат")},
        "words": [
            ("time", "/taɪm/", "n.", "vaqt", "время", "вақт"),
            ("hour", "/aʊr/", "n.", "soat (davomiylik)", "час", "соат"),
            ("now", "/naʊ/", "adv.", "hozir", "сейчас", "ҳозир"),
            ("early", "/ˈɜːrli/", "adj.", "erta", "рано", "барвақт"),
            ("late", "/leɪt/", "adj.", "kech", "поздно", "дер"),
            ("o'clock", "/əˈklɒk/", "adv.", "soat (aniq)", "часов (ровно)", "соат (дақиқ)"),
            ("What time", "/wɒt taɪm/", "expr.", "soat nechada", "во сколько", "соати чанд"),
            ("minute", "/ˈmɪnɪt/", "n.", "daqiqa", "минута", "дақиқа"),
        ],
        "grammar": [
            {"title": L("Soatni aytish", "Как назвать время", "Гуфтани вақт"), "title_en": "telling time",
             "rule": L("It is three o'clock.\nWhat time is it? — soat nechada?\nMisol: It's ten o'clock.", "It is three o'clock.\nWhat time is it?\nПример: It's ten o'clock.", "It is three o'clock.\nWhat time is it?\nМисол: It's ten o'clock.")},
            {"title": L("early / late / now", "early / late / now", "early / late / now"), "title_en": "time adverbs",
             "rule": L("now — hozir, early — erta, late — kech.\nMisol: I am late. Come now.", "now — сейчас, early — рано, late — поздно.\nПример: I am late.", "now — ҳозир, early — барвақт, late — дер.\nМисол: I am late.")},
        ],
        "sentence_builder": {"sentence": L("«Soat uch.»", "«Три часа.»", "«Соат се.»"), "tokens": ["is", "It", "o'clock", "three", "time"], "answer_tokens": ["It", "is", "three", "o'clock"], "explanation": L("It is ... o'clock — aniq soat.", "It is ... o'clock — ровно.", "It is ... o'clock — соати дақиқ.")},
        "quiz_grammar": {"prompt": L("«Hozir» — inglizchada qaysi?", "«Сейчас» — как по-английски?", "«Ҳозир» — ба англисӣ кадом?"), "options": ["late", "now", "early", "time"], "correct_index": 1},
        "listen_practice": {"audio_text": "It is three o'clock.", "pinyin": "/ɪt ɪz θriː əˈklɒk/", "options": ["What time is it?", "It is three o'clock.", "I am late.", "Come now."], "correct_index": 1, "explanation": L("o'clock — aniq soat.", "o'clock — ровно.", "o'clock — соати дақиқ.")},
        "pronunciation": {"phrase": "What time is it now", "pinyin": "/wɒt taɪm ɪz ɪt naʊ/", "translation": L("Hozir soat nechada", "Сколько сейчас времени", "Ҳозир соат чанд аст")},
        "listen_dialog": {"audio_text": "I am late!", "pinyin": "/aɪ æm leɪt/", "options": ["I am late!", "It is early.", "What time is it?", "Come now."], "correct_index": 0, "explanation": L("late = kech.", "late = поздно.", "late = дер.")},
        "gap_fill": {"sentence": "It is ten ____.", "options": ["time", "o'clock", "now", "late"], "correct_index": 1, "explanation": L("aniq soat — o'clock.", "ровно — o'clock.", "соати дақиқ — o'clock.")},
        "dialog_cloze": {"lines": [{"speaker": "A", "zh": "What time is it?", "blank": False}, {"speaker": "B", "zh": "", "blank": True}], "options": ["It is five o'clock.", "Nice to meet you!", "I like tea.", "Goodbye!"], "correct_index": 0, "explanation": L("Vaqtni 'It is ... o'clock' bilan.", "Время — 'It is ... o'clock'.", "Вақт — 'It is ... o'clock'.")},
        "quiz_dialog": {"prompt": L("Qaysi biri vaqt so'zi emas?", "Что не слово о времени?", "Кадомаш калимаи вақт нест?"), "options": ["hour", "minute", "shop", "now"], "correct_index": 2},
        "dialogues": [
            {"scene": L("Soat", "Часы", "Соат"), "lines": [("A", "What time is it?", "/wɒt taɪm ɪz ɪt/", "Soat nechada?", "Сколько времени?", "Соат чанд аст?"), ("B", "It is five o'clock.", "/ɪt ɪz faɪv əˈklɒk/", "Soat besh.", "Пять часов.", "Соат панҷ.")]},
            {"scene": L("Kechikish", "Опоздание", "Дер мондан"), "lines": [("A", "Come now, we are late!", "/kʌm naʊ wiː ɑːr leɪt/", "Hozir keling, kechikyapmiz!", "Идём, мы опаздываем!", "Ҳозир биёед, дер мондем!"), ("B", "OK, one minute!", "/wʌn ˈmɪnɪt/", "Xo'p, bir daqiqa!", "Хорошо, минуту!", "Хуб, як дақиқа!")]},
            {"scene": L("Erta", "Рано", "Барвақт"), "lines": [("A", "You are early!", "/juː ɑːr ˈɜːrli/", "Erta kelibsiz!", "Вы рано!", "Шумо барвақт омадед!"), ("B", "Yes, I have time.", "/aɪ hæv taɪm/", "Ha, vaqtim bor.", "Да, у меня есть время.", "Бале, вақт дорам.")]},
        ],
    },
    {
        "level": "hsk1", "id": 11, "title": "Weather",
        "sub": L("Ob-havo va 'It is' bilan tavsif", "Погода и описание через 'It is'", "Обу ҳаво ва тавсиф бо 'It is'"),
        "manifest": {"title": "Weather", "py": "/ˈweðər/", "tr": L("Ob-havo so'zlari", "Слова о погоде", "Калимаҳои обу ҳаво")},
        "words": [
            ("weather", "/ˈweðər/", "n.", "ob-havo", "погода", "обу ҳаво"),
            ("hot", "/hɒt/", "adj.", "issiq", "жарко", "гарм"),
            ("cold", "/koʊld/", "adj.", "sovuq", "холодно", "хунук"),
            ("warm", "/wɔːrm/", "adj.", "iliq", "тепло", "гарм (мулоим)"),
            ("rain", "/reɪn/", "n.", "yomg'ir", "дождь", "борон"),
            ("sunny", "/ˈsʌni/", "adj.", "quyoshli", "солнечно", "офтобӣ"),
            ("wind", "/wɪnd/", "n.", "shamol", "ветер", "шамол"),
            ("cloud", "/klaʊd/", "n.", "bulut", "облако", "абр"),
        ],
        "grammar": [
            {"title": L("Ob-havoni aytish", "Как сказать о погоде", "Гуфтани обу ҳаво"), "title_en": "describing weather",
             "rule": L("It is hot. It is cold. It is sunny.\nYomg'ir uchun: It is raining.\nMisol: Today it is warm.", "It is hot. It is cold. It is sunny.\nДождь: It is raining.\nПример: Today it is warm.", "It is hot. It is cold.\nБорон: It is raining.\nМисол: Today it is warm.")},
            {"title": L("How is the weather?", "How is the weather?", "How is the weather?"), "title_en": "weather question",
             "rule": L("So'rash: How is the weather?\nJavob: It is sunny.", "Спросить: How is the weather?\nОтвет: It is sunny.", "Пурсидан: How is the weather?\nҶавоб: It is sunny.")},
        ],
        "sentence_builder": {"sentence": L("«Bugun issiq.»", "«Сегодня жарко.»", "«Имрӯз гарм аст.»"), "tokens": ["is", "Today", "cold", "hot", "it"], "answer_tokens": ["Today", "it", "is", "hot"], "explanation": L("It is + sifat — ob-havo.", "It is + прилаг. — погода.", "It is + сифат — обу ҳаво.")},
        "quiz_grammar": {"prompt": L("«Sovuq» — inglizchada qaysi?", "«Холодно» — как по-английски?", "«Хунук» — ба англисӣ кадом?"), "options": ["hot", "cold", "warm", "wind"], "correct_index": 1},
        "listen_practice": {"audio_text": "It is sunny today.", "pinyin": "/ɪt ɪz ˈsʌni təˈdeɪ/", "options": ["It is cold.", "It is sunny today.", "It is raining.", "How is the weather?"], "correct_index": 1, "explanation": L("sunny = quyoshli.", "sunny = солнечно.", "sunny = офтобӣ.")},
        "pronunciation": {"phrase": "It is cold today", "pinyin": "/ɪt ɪz koʊld təˈdeɪ/", "translation": L("Bugun sovuq", "Сегодня холодно", "Имрӯз хунук аст")},
        "listen_dialog": {"audio_text": "How is the weather?", "pinyin": "/haʊ ɪz ðə ˈweðər/", "options": ["How is the weather?", "It is hot.", "It is raining.", "A cold wind."], "correct_index": 0, "explanation": L("How is the weather = ob-havo qanday.", "How is the weather = какая погода.", "How is the weather = обу ҳаво чӣ хел.")},
        "gap_fill": {"sentence": "It ____ cold today.", "options": ["am", "is", "are", "weather"], "correct_index": 1, "explanation": L("It is + sifat.", "It is + прилаг.", "It is + сифат.")},
        "dialog_cloze": {"lines": [{"speaker": "A", "zh": "How is the weather?", "blank": False}, {"speaker": "B", "zh": "", "blank": True}], "options": ["It is sunny.", "My name is Tom.", "I am ten.", "Goodbye!"], "correct_index": 0, "explanation": L("Ob-havoni 'It is ...' bilan.", "Погода — 'It is ...'.", "Обу ҳаво — 'It is ...'.")},
        "quiz_dialog": {"prompt": L("Qaysi biri ob-havo emas?", "Что не о погоде?", "Кадомаш обу ҳаво нест?"), "options": ["rain", "sunny", "school", "wind"], "correct_index": 2},
        "dialogues": [
            {"scene": L("Ob-havo", "Погода", "Обу ҳаво"), "lines": [("A", "How is the weather?", "/haʊ ɪz ðə ˈweðər/", "Ob-havo qanday?", "Какая погода?", "Обу ҳаво чӣ хел?"), ("B", "It is sunny.", "/ɪt ɪz ˈsʌni/", "Quyoshli.", "Солнечно.", "Офтобӣ.")]},
            {"scene": L("Sovuq kun", "Холодный день", "Рӯзи хунук"), "lines": [("A", "It is cold today.", "/ɪt ɪz koʊld/", "Bugun sovuq.", "Сегодня холодно.", "Имрӯз хунук."), ("B", "Yes, a cold wind.", "/ə koʊld wɪnd/", "Ha, sovuq shamol.", "Да, холодный ветер.", "Бале, шамоли хунук.")]},
            {"scene": L("Yomg'ir", "Дождь", "Борон"), "lines": [("A", "It is raining.", "/ɪt ɪz ˈreɪnɪŋ/", "Yomg'ir yog'yapti.", "Идёт дождь.", "Борон меборад."), ("B", "Take an umbrella!", "/teɪk ən ʌmˈbrelə/", "Soyabon oling!", "Возьмите зонт!", "Соябон гиред!")]},
        ],
    },
]
